osx_image: xcode10.2
language: swift
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example/WLEmptyState.xcworkspace
  - SCHEME=WLEmptyState-Example
  - SDK=iphonesimulator12.2
  - DESTINATION="OS=12.2,name=iPhone XS"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" ONLY_ACTIVE_ARCH=NO | xcpretty
  - xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO
